[package]
name = "polygon"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smart-default = "0.6.0"
eframe = "0.15.0"
earcutr = "0.2.0"
cgmath = "0.17.0"
spade = "1.8.2"
nalgebra = "0.29.0"